import type { ScenarioDifficulty } from "@/lib/scenarios/scenarioLibrary";
import type { MediaAsset } from "./media";
import type { ScenarioSpeaker } from "./simulation";

/** One of OpenAI's preset TTS voices. */
export type OpenAiVoiceId =
  | "alloy"
  | "ash"
  | "ballad"
  | "coral"
  | "echo"
  | "fable"
  | "nova"
  | "onyx"
  | "sage"
  | "shimmer"
  | "verse";

/**
 * The voice a single character speaks with. Pinned once when the scenario is
 * created so the same character never drifts between perceived genders, and
 * carried through every TTS call for that speaker.
 */
export type CharacterVoice = {
  voiceId: OpenAiVoiceId;
  /** Baseline emotional state, used to build the TTS delivery instruction. */
  emotion: string;
};

export type Scenario = {
  id: string;
  title: string;
  setting: string;
  summary: string;
  patientProfile: string;
  patientEmotion: string;
  familyEmotion?: string;
  traineeObjective: string;
  communicationChallenge: string;
  startingSituation: string;
  firstPrompt: string;
  suggestedTurns: number;
  endingCondition: string;
  evaluationCriteria: string[];
  defaultEvaluationCriteria?: string[];
  mediaAssets?: MediaAsset[];
  /** Optional so scenarios saved before voice pinning still load. */
  characterVoices?: Partial<Record<ScenarioSpeaker, CharacterVoice>>;

  /*
   * Progress-tracking metadata. Set on the client from the library case the
   * trainer picked and the tier they chose — NEVER generated by the model. If
   * these came out of Gemini it would invent a difficulty for every scenario
   * and the cohort comparison buckets would be fiction.
   *
   * All optional so scenarios saved before this existed still load.
   */

  /** The `LibraryScenario.id` this was generated from, if any. */
  libraryId?: string;
  /** Track name, e.g. "Breaking bad news". Carried from the library case. */
  category?: string;
  /** Chosen by the trainer; defaults to the library case's tier. */
  difficulty?: ScenarioDifficulty;
};
