export type GeminiSchema = {
  type: "OBJECT" | "ARRAY" | "STRING" | "NUMBER" | "INTEGER" | "BOOLEAN";
  description?: string;
  properties?: Record<string, GeminiSchema>;
  items?: GeminiSchema;
  required?: string[];
  enum?: string[];
  nullable?: boolean;
  minItems?: number;
  maxItems?: number;
};

const stringArraySchema: GeminiSchema = {
  type: "ARRAY",
  items: { type: "STRING" },
};

export const scenarioSchema: GeminiSchema = {
  type: "OBJECT",
  required: [
    "id",
    "title",
    "setting",
    "summary",
    "patientProfile",
    "patientEmotion",
    "traineeObjective",
    "communicationChallenge",
    "startingSituation",
    "firstPrompt",
    "suggestedTurns",
    "endingCondition",
    "evaluationCriteria",
    "mediaAssets",
  ],
  properties: {
    id: { type: "STRING" },
    title: { type: "STRING" },
    setting: { type: "STRING" },
    summary: { type: "STRING" },
    patientProfile: { type: "STRING" },
    patientEmotion: { type: "STRING" },
    familyEmotion: { type: "STRING", nullable: true },
    traineeObjective: { type: "STRING" },
    communicationChallenge: { type: "STRING" },
    startingSituation: { type: "STRING" },
    firstPrompt: { type: "STRING" },
    suggestedTurns: { type: "INTEGER" },
    endingCondition: { type: "STRING" },
    evaluationCriteria: stringArraySchema,
    mediaAssets: {
      type: "ARRAY",
      items: {
        type: "OBJECT",
        properties: {},
      },
    },
  },
};

export const nextSimulationTurnSchema: GeminiSchema = {
  type: "OBJECT",
  required: ["speaker", "message", "tensionLevel", "shouldEnd"],
  properties: {
    speaker: {
      type: "STRING",
      enum: ["patient", "family_member", "nurse", "bystander", "narrator"],
    },
    message: { type: "STRING" },
    tensionLevel: {
      type: "STRING",
      enum: ["low", "medium", "high"],
    },
    shouldEnd: { type: "BOOLEAN" },
  },
};

export const feedbackReportSchema: GeminiSchema = {
  type: "OBJECT",
  required: [
    "overallScore",
    "summary",
    "whatWentWell",
    "whatCouldImprove",
    "communicationGaps",
    "betterResponses",
    "finalAdvice",
  ],
  properties: {
    overallScore: { type: "INTEGER" },
    summary: { type: "STRING" },
    whatWentWell: stringArraySchema,
    whatCouldImprove: stringArraySchema,
    communicationGaps: stringArraySchema,
    betterResponses: stringArraySchema,
    finalAdvice: { type: "STRING" },
  },
};

/** Delivery coaching is generated by its own call, with its own schema. */
export const deliveryFeedbackSchema: GeminiSchema = {
  type: "OBJECT",
  required: ["deliveryFeedback"],
  properties: {
    deliveryFeedback: stringArraySchema,
  },
};

const customCriterionItemSchema: GeminiSchema = {
  type: "OBJECT",
  required: ["criterion", "assessment"],
  properties: {
    criterion: { type: "STRING" },
    assessment: { type: "STRING" },
  },
};

/**
 * The feedback report schema, optionally extended with the custom-criteria
 * section. When a trainer added custom criteria, the main report and the
 * custom-criteria assessments are produced by a SINGLE Gemini call using this
 * combined schema. One reasoning pass over the transcript yields both sections,
 * which is what structurally prevents them from reaching opposite verdicts about
 * the same behavior. With no custom criteria, this is just feedbackReportSchema.
 */
export function buildFeedbackReportSchema(customCriteriaCount: number): GeminiSchema {
  if (customCriteriaCount <= 0) {
    return feedbackReportSchema;
  }

  return {
    ...feedbackReportSchema,
    required: [...(feedbackReportSchema.required ?? []), "customCriteriaFeedback"],
    properties: {
      ...feedbackReportSchema.properties,
      customCriteriaFeedback: {
        type: "ARRAY",
        minItems: customCriteriaCount,
        maxItems: customCriteriaCount,
        items: customCriterionItemSchema,
      },
    },
  };
}
